version: "3.8"

services:
  web:
    image: your_django_image:latest # Replace with your actual Django image
    build:
      context: .
      dockerfile: Dockerfile # Specify the Dockerfile to use
    volumes:
      - .:/app # Mount your app directory
    environment:
      - DEBUG=${DEBUG} # Set to False in production
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}

    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000 # Change this for production

  redis:
    image: redis:alpine
    ports:
      - "6379"

  celery:
    image: your_django_image:latest # Use the same image as your Django app
    build:
      context: .
      dockerfile: Dockerfile # Specify the Dockerfile to use
    command: celery -A classattendance worker --loglevel=info # Replace with your project name
    depends_on:
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dbname # Replace with your database name
      POSTGRES_USER: user # Replace with your database user
      POSTGRES_PASSWORD: password # Replace with your database password
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
