# Generated by Django 5.1.7 on 2025-03-08 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRegistrationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_face', models.ImageField(blank=True, null=True, upload_to='media/face_images/front/')),
                ('left_face', models.ImageField(blank=True, null=True, upload_to='media/face_images/left/')),
                ('right_face', models.ImageField(blank=True, null=True, upload_to='media/face_images/right/')),
                ('is_front_face_approved', models.BooleanField(default=False, null=True)),
                ('is_left_face_approved', models.BooleanField(default=False, null=True)),
                ('is_right_face_approved', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='media/profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TempRegistration',
        ),
        migrations.AddField(
            model_name='student',
            name='frontal_face_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='left_face_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='right_face_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
