# Generated by Django 5.1.7 on 2025-03-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_faceregistrationimage_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceregistrationimage',
            name='is_front_face_rejected',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='faceregistrationimage',
            name='is_left_face_rejected',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='faceregistrationimage',
            name='is_right_face_rejected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
