# Generated by Django 5.1.7 on 2025-03-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_faceregistrationimage_is_front_face_rejected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceregistrationimage',
            name='is_front_face_approved',
        ),
        migrations.RemoveField(
            model_name='faceregistrationimage',
            name='is_front_face_rejected',
        ),
        migrations.RemoveField(
            model_name='faceregistrationimage',
            name='is_left_face_approved',
        ),
        migrations.RemoveField(
            model_name='faceregistrationimage',
            name='is_left_face_rejected',
        ),
        migrations.RemoveField(
            model_name='faceregistrationimage',
            name='is_right_face_approved',
        ),
        migrations.RemoveField(
            model_name='faceregistrationimage',
            name='is_right_face_rejected',
        ),
        migrations.AddField(
            model_name='faceregistrationimage',
            name='front_face_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faceregistrationimage',
            name='left_face_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faceregistrationimage',
            name='right_face_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
