# Generated by Django 5.1.7 on 2025-03-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_faceregistrationimage_is_front_face_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceregistrationimage',
            name='front_face',
            field=models.ImageField(blank=True, null=True, upload_to='face_images/front/'),
        ),
        migrations.AlterField(
            model_name='faceregistrationimage',
            name='left_face',
            field=models.ImageField(blank=True, null=True, upload_to='face_images/left/'),
        ),
        migrations.AlterField(
            model_name='faceregistrationimage',
            name='right_face',
            field=models.ImageField(blank=True, null=True, upload_to='face_images/right/'),
        ),
    ]
